#!/usr/bin/env bash

set -euo pipefail

expected_name="${AGENT_AUTHOR_NAME:-Codex}"
expected_email="${AGENT_AUTHOR_EMAIL:-codex@openai.com}"
prompted_by_name="${PROMPTED_BY_NAME:-}"
prompted_by_email="${PROMPTED_BY_EMAIL:-}"
generated_by_agent="${CODING_AGENT_NAME:-$expected_name}"
generated_by_model="${CODING_AGENT_MODEL_VERSION:-${CODING_AGENT_MODEL:-}}"
generated_by_args="${CODING_AGENT_MODEL_PARAMS:-}"

if [[ "${1:-}" == "--hook" ]]; then
  hook_name="${2:-unknown-hook}"
  msg_file="${3:-}"

  author_ident="$(git var GIT_AUTHOR_IDENT 2>/dev/null || true)"
  actual_name="${author_ident%% <*}"
  actual_email="${author_ident#*<}"
  actual_email="${actual_email%%>*}"

  if [[ "$actual_name" != "$expected_name" || "$actual_email" != "$expected_email" ]]; then
    echo "error: $hook_name requires git identity $expected_name <$expected_email>." >&2
    echo "current: ${actual_name:-<unset>} <${actual_email:-<unset>}>" >&2
    exit 1
  fi

  if [[ "$hook_name" == "commit-msg" ]]; then
    if [[ -z "$msg_file" || ! -f "$msg_file" ]]; then
      echo "error: commit-msg hook missing commit message file." >&2
      exit 1
    fi

    expected_prompted="Prompted By: $prompted_by_name <$prompted_by_email>"
    expected_generated="Generated By: $generated_by_agent $generated_by_model $generated_by_args"
    if ! grep -Fqx "$expected_prompted" "$msg_file"; then
      echo "error: commit message must include trailer:" >&2
      echo "  $expected_prompted" >&2
      exit 1
    fi

    if ! grep -Fqx "$expected_generated" "$msg_file"; then
      echo "error: commit message must include trailer:" >&2
      echo "  $expected_generated" >&2
      exit 1
    fi
  fi

  exit 0
fi

for arg in "$@"; do
  if [[ "$arg" == "--no-verify" ]]; then
    echo "error: --no-verify is blocked for agent commits." >&2
    exit 1
  fi
done

exec git \
  -c "user.name=$expected_name" \
  -c "user.email=$expected_email" \
  commit "$@"
